version: 2 
jobs:
  test:
    working_directory: /go/src/github.com/burrbd/dip
    docker:
    - image: circleci/golang:1.15
    steps:
    - checkout
    - run: go test -v -cover -race ./...
workflows:
  version: 2
  build-workflow:
    jobs:
      - test

